### PR TITLE
updated characters and son of Arjuna

### PR DESCRIPTION
**Pull request by sharmavipul9756**

### CODE REVIEW

**Review by Abhiramborige — COMMENTED** [review]
Dude, why there are more than 22k lines modified in package-lock.json for just some changes in character_details.json?

**Comment by Abhiramborige** [comment]
Could you please add some more characters rather than adding the relations.

**Comment by sharmavipul9756** [comment]
yes I will update

**Comment by Abhiramborige** [comment]
Hey, there are some merge conflicts raised, I would like to close this PR. Sorry and thanks for the contrib.

**Pull request closed without merging**
