### PR TITLE
✨add a sidebar

### PR DESCRIPTION
**Pull request by daptheHuman**
#1 Navbar sidebar for mobile version

### CODE REVIEW

**Comment by Abhiramborige** [comment]
Dude, make the indentation to 2 spaces and please use scss if possible. 
I am getting merge conflict.
Please modify it.

**Comment by Abhiramborige** [comment]
The resolve conflicts button is disabled and there is only single option to resolve conflict using command line, but not opening the editor,

**Comment by daptheHuman** [comment]
It’s done and dusted.😉

**Comment by Abhiramborige** [comment]
Please make the indentation as 2 spaces.
2 tabs is weird. Please

**Comment by daptheHuman** [comment]
> Please make the indentation as 2 spaces. 2 tabs is weird. Please

but I can't commit indent changes, vscode/git doesn't detect any changes

**Comment by daptheHuman** [comment]
if you know how, just let me know

**Comment by Abhiramborige** [comment]
> > Please make the indentation as 2 spaces. 2 tabs is weird. Please
> 
> but I can't commit indent changes, vscode/git doesn't detect any changes

oh fine, no issues then

**Comment by Abhiramborige** [comment]
thanks for the contribution!

**Comment by daptheHuman** [comment]
> > > Please make the indentation as 2 spaces. 2 tabs is weird. Please
> > 
> > 
> > but I can't commit indent changes, vscode/git doesn't detect any changes
> 
> oh fine, no issues then

maybe only you (the owner) can edit the file on Github then change the spaces🤔

**Comment by Abhiramborige** [comment]
> > > > Please make the indentation as 2 spaces. 2 tabs is weird. Please
> > > 
> > > 
> > > but I can't commit indent changes, vscode/git doesn't detect any changes
> > 
> > 
> > oh fine, no issues then
> 
> maybe only you (the owner) can edit the file on Github then change the spaces🤔

yeah I will do that, no worries

**Pull request merged**
