### PR TITLE
Feat add more enhancement

### PR DESCRIPTION
**Pull request by daptheHuman**
#1 Last requests

### CODE REVIEW

**Comment by Abhiramborige** [comment]
thanks !

**Comment by Abhiramborige** [comment]
dude !
image
plase check this, now its not visible even in dark mode

**Comment by Abhiramborige** [comment]
there is an issue with opacity, please look into that.

**Comment by Abhiramborige** [comment]
I have fixed it, no worries.

**Comment by daptheHuman** [comment]
> there is an issue with opacity, please look into that.

which one?

**Comment by Abhiramborige** [comment]
> > there is an issue with opacity, please look into that.
> 
> which one?

no, I fixed it, no worries now

**Pull request merged**
