### PR TITLE
CSS to Sass. #9

### PR DESCRIPTION
**Pull request by RShalman**

### CODE REVIEW

**Comment by Abhiramborige** [comment]
image

**Comment by Abhiramborige** [comment]
Something like this must come in the forked repo in your github, but why there is no scss but only css.

**Comment by Abhiramborige** [comment]
could you please send the screenshots of all
1. homepage
2. connect page
3. about page
4. any character after clicking
Please dude, don't feel bad for that but please, I am not getting this.

**Comment by RShalman** [comment]
> Something like this must come in the forked repo in your github, but why there is no scss but only css.

Don't know what you're talking about. My PR goes with scss instead of previous css files and according changes.
Answered you inside issue.

**Comment by Abhiramborige** [comment]
Thanks for contribution!

**Comment by Abhiramborige** [comment]
Thanks for contribution!

**Pull request merged**
